# A detailed description for all parameters can be found in BenchmarkOptions.h

parameters:
    name: FullBenchmark
    runs: 25
    group: panda_arm      # Required
    timeout: 1.0
    output_directory: /tmp/moveit_benchmarks/
    start_states_regex: ready
planning_pipelines:
  # Benchmark tool
  pipelines: [ANYTIME1, ANYTIME2 ,ANYTIME3]
  ANYTIME1:
    name: ompl
    planners:
      - AnytimePathShortening1
  ANYTIME2:
     name: ompl_2
     planners:
       - AnytimePathShortening2
  ANYTIME3:
     name: ompl_3
     planners:
       - AnytimePathShortening3
  parallel_pipelines: [ompl_rrtc]
  ompl_rrtc:
    pipelines: [ompl_4]
    planner_ids: [RRTConnectkConfigDefault]
