# A detailed description for all parameters can be found in BenchmarkOptions.h

parameters:
    name: FullBenchmark
    runs: 25
    group: panda_arm      # Required
    timeout: 1.0
    output_directory: /tmp/moveit_benchmarks/
    start_states_regex: ready
planning_pipelines:
  # Benchmark tool
  pipelines: [OMPL_RRTC, ANYTIME]
  OMPL_RRTC:
    name: ompl
    planners:
      - RRTConnectkConfigDefault
  ANYTIME:
     name: ompl_2
     planners:
       - AnytimePathShortening
  parallel_pipelines: [parallel_rrtc]
  parallel_rrtc:
    pipelines: [ompl_3, ompl_4, ompl_5, ompl_6]
    planner_ids: [RRTConnectkConfigDefault, RRTConnectkConfigDefault, RRTConnectkConfigDefault, RRTConnectkConfigDefault]
