# A detailed description for all parameters can be found in BenchmarkOptions.h

parameters:
    name: FullBenchmark
    runs: 25
    group: panda_arm      # Required
    timeout: 1.0
    output_directory: /tmp/moveit_benchmarks/
    start_states_regex: ready
planning_pipelines:
  # Benchmark tool
  pipelines: [OMPL_RRTC, ANYTIME1, ANYTIME2]
  OMPL_RRTC:
    name: ompl
    planners:
      - RRTConnectkConfigDefault
  ANYTIME1:
     name: ompl_2
     planners:
       - AnytimePathShortening1
  ANYTIME2:
     name: ompl_3
     planners:
       - AnytimePathShortening2
  parallel_pipelines: [ANYTIME3]
  ANYTIME3:
    pipelines: [ompl_4]
    planner_ids: [AnytimePathShortening3]
